import { Category } from '../@types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat_salario',
    name: 'Salário',
    icon: 'cash-outline',
    color: '#10B981',
    type: 'income',
    isDefault: true,
  },
  {
    id: 'cat_investimentos',
    name: 'Investimentos',
    icon: 'trending-up-outline',
    color: '#06B6D4',
    type: 'income',
    isDefault: true,
  },
  {
    id: 'cat_alimentacao',
    name: 'Alimentação',
    icon: 'restaurant-outline',
    color: '#F59E0B',
    type: 'expense',
    isDefault: true,
  },
  {
    id: 'cat_transporte',
    name: 'Transporte',
    icon: 'car-outline',
    color: '#3B82F6',
    type: 'expense',
    isDefault: true,
  },
  {
    id: 'cat_moradia',
    name: 'Moradia',
    icon: 'home-outline',
    color: '#8B5CF6',
    type: 'expense',
    isDefault: true,
  },
  {
    id: 'cat_saude',
    name: 'Saúde',
    icon: 'medkit-outline',
    color: '#EC4899',
    type: 'expense',
    isDefault: true,
  },
  {
    id: 'cat_lazer',
    name: 'Lazer',
    icon: 'game-controller-outline',
    color: '#14B8A6',
    type: 'expense',
    isDefault: true,
  },
  {
    id: 'cat_educacao',
    name: 'Educação',
    icon: 'school-outline',
    color: '#6366F1',
    type: 'expense',
    isDefault: true,
  },
  {
    id: 'cat_outros',
    name: 'Outros',
    icon: 'ellipsis-horizontal-circle-outline',
    color: '#64748B',
    type: 'both',
    isDefault: true,
  },
];

export const CATEGORY_ICONS_LIST = [
  'restaurant-outline',
  'car-outline',
  'home-outline',
  'medkit-outline',
  'game-controller-outline',
  'school-outline',
  'cash-outline',
  'cart-outline',
  'fitness-outline',
  'airplane-outline',
  'gift-outline',
  'shirt-outline',
  'construct-outline',
  'trending-up-outline',
  'paw-outline',
  'wifi-outline',
  'film-outline',
  'cafe-outline',
];

export const CATEGORY_COLORS_LIST = [
  '#10B981',
  '#3B82F6',
  '#F59E0B',
  '#EF4444',
  '#8B5CF6',
  '#EC4899',
  '#14B8A6',
  '#06B6D4',
  '#6366F1',
  '#F97316',
  '#84CC16',
  '#64748B',
];
